[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
upload_port = COM6
monitor_port = COM6
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    Links2004/WebSockets @ ^2.4.1
